---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/gmussyco/public_html/basedev/
    - /bin/cp -R out/_next $DEPLOYPATH
    - /bin/cp -R out/fonts $DEPLOYPATH
    - /bin/cp out/index.html $DEPLOYPATH
    - /bin/cp out/logo_bg.png $DEPLOYPATH

